### ISSUE TITLE
setValidationQuery is now deprecated.

### ISSUE THREAD

**Issue by lamduong33** [mdeinum/blog-database-up#1]
setValidationQuery() method is now deprecated with the DatabaseStartupValidator class. Documentation refers to the "JDBC 4.0 connection validation" method as replacement, but I cannot find anything on this. What's the best way to tackle problem in 2022?

**Comment by mdeinum** [comment]
Don't use validation query, it will use the JDBC 4 connection validation by default (and should be preferred). This is also noted in the deprecation notice on the said class. See https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/jdbc/support/DatabaseStartupValidator.html#setValidationQuery-java.lang.String-. 

This is also mentioned in the blog post you react to :). 

Also you shouldn't use issue trackers to ask questions, use stackoverflow for that.
